[Interface]
Address = 100.85.43.213/32
DNS = 100.64.0.1, 8.8.4.4
PrivateKey = u17LTYQ2zS8qpwfvXB6bEhOs3d1b6pVNirEc4MKUiFg=

[Peer]
PublicKey = /AMKpnrTaXhLMofacUtTX3uQA7J0pR5Cc1Lq3H2P9Rk=
PresharedKey = cAHjbE2wrnV+vDVkX0Ep2GdCBLCt7oy2R2shPPIM2GU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 89.105.199.147:9408
PersistentKeepalive = 25
